# AWS RDS 인스턴스와 Redis 서비스를 사용하지 않았습니다.
spring:
  datasource:
    url: jdbc:mysql://<RDS_HOST>:3306/msa?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&characterEncoding=UTF-8
    username: <RDS_USERNAME>
    password: <RDS_PASSWORD>
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: false
        format_sql: false
        use_sql_comments: false
  data:
    redis:
      host: <REDIS_HOST>  # 운영 환경 Redis 주소
      port: 6379
      username: default
      password: "<REDIS_PASSWORD>"